[package]
name = "maligno-rs"
version = "0.12.0"
edition = "2024"

[[bin]]
name = "maligno"
path = "src/main.rs"

[dependencies]
clap     = { version = "4", features = ["derive"] }
anyhow   = "1"
flate2   = "1"
ext-sort = { version = "0.1", features = ["memory-limit"] }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
